controllers:
  resource: ../src/Controller/
  type: annotation

kernel:
  resource: ../src/Kernel.php
  type: annotation

api_index:
  path: /
  controller: App\Controller\ApiController::index
  methods: GET


# --- Admin routes ---

# PLAYERS

admin_get_players:
  path: /admin/players
  controller: App\Controller\AdminPlayerController::getAllPlayers
  methods: GET

admin_get_player:
  path: /admin/players/{id}
  controller: App\Controller\AdminPlayerController::getPlayer
  methods: GET

admin_get_player_games:
  path: /admin/players/{id}/games
  controller: App\Controller\AdminPlayerController::getPlayerGames
  methods: GET

admin_post_player:
  path: /admin/players
  controller: App\Controller\AdminPlayerController::postPlayer
  methods: POST

admin_patch_player:
  path: /admin/players/{id}
  controller: App\Controller\AdminPlayerController::patchPlayer
  methods: PATCH

admin_delete_player:
  path: /admin/players/{id}
  controller: App\Controller\AdminPlayerController::deletePlayer
  methods: DELETE

# GAMES

admin_get_games:
  path: /admin/games
  controller: App\Controller\AdminGameController::getAllGames
  methods: GET

admin_get_game:
  path: /admin/games/{id}
  controller: App\Controller\AdminGameController::getGame
  methods: GET

admin_post_game:
  path: /admin/games
  controller: App\Controller\AdminGameController::postGame
  methods: POST

admin_patch_game:
  path: /admin/games/{id}
  controller: App\Controller\AdminGameController::patchGame
  methods: PATCH

admin_delete_game:
  path: /admin/games/{id}
  controller: App\Controller\AdminGameController::deleteGame
  methods: DELETE

# --- Front routes ---

# PLAYERS

api_register_player:
  path: /api/register
  controller: App\Controller\FrontPlayerController::registerPlayer
  methods: POST

api_login_player:
  path: /api/login
  controller: App\Controller\FrontPlayerController::loginPlayer
  methods: PATCH

api_update_player:
  path: /api/player_settings
  controller: App\Controller\FrontPlayerController::updatePlayer
  methods: PATCH

api_delete_player_account:
  path: /api/delete_account
  controller: App\Controller\FrontPlayerController::deletePlayerAccount
  methods: DELETE

# PLAYERS_GAMES

api_create_game:
  path: /api/create_game
  controller: App\Controller\FrontPlayerGameController::createGame
  methods: POST

api_login_game:
  path: /api/join_game
  controller: App\Controller\FrontPlayerGameController::joinGame
  methods: PATCH

api_start_game:
  path: /api/start_game
  controller: App\Controller\FrontPlayerGameController::startGame
  methods: PATCH

# GAMES

api_roll_dices:
  path: /api/roll_dices
  controller: App\Controller\FrontGameController::rollDices
  methods: PATCH

api_set_bid:
  path: /api/make_bid
  controller: App\Controller\FrontGameController::setBid
  methods: PATCH

api_get_last_bid:
  path: /api/get_bid
  controller: App\Controller\FrontGameController::getLastBid
  methods: GET

api_get_last_roll:
  path: /api/get_roll
  controller: App\Controller\FrontGameController::getLastRoll
  methods: GET