controllers:
  resource: ../src/Controller/
  type: annotation

kernel:
  resource: ../src/Kernel.php
  type: annotation

api_index:
  path: /
  controller: App\Controller\ApiController::index
  methods: GET


# --- Admin routes ---

# PLAYERS

admin_get_players:
  path: /admin/players
  controller: App\Controller\PlayerController::getAllPlayers
  methods: GET

admin_get_player:
  path: /admin/players/{id}
  controller: App\Controller\PlayerController::getPlayer
  methods: GET

admin_get_player_games:
  path: /admin/players/{id}/games
  controller: App\Controller\PlayerController::getPlayerGames
  methods: GET

admin_post_player:
  path: /admin/players
  controller: App\Controller\PlayerController::postPlayer
  methods: POST

admin_patch_player:
  path: /admin/players/{id}
  controller: App\Controller\PlayerController::patchPlayer
  methods: PATCH

admin_delete_player:
  path: /admin/players/{id}
  controller: App\Controller\PlayerController::deletePlayer
  methods: DELETE

# GAMES

admin_get_games:
  path: /admin/games
  controller: App\Controller\GameController::getAllGames
  methods: GET

admin_get_game:
  path: /admin/games/{id}
  controller: App\Controller\GameController::getGame
  methods: GET

admin_post_game:
  path: /admin/games
  controller: App\Controller\GameController::postGame
  methods: POST

admin_patch_game:
  path: /admin/games/{id}
  controller: App\Controller\GameController::patchGame
  methods: PATCH

admin_delete_game:
  path: /admin/games/{id}
  controller: App\Controller\GameController::deleteGame
  methods: DELETE

# --- Front routes ---

# PLAYERS

api_register_player:
  path: /api/register
  controller: App\Controller\FrontController::registerPlayer
  methods: POST

api_login_player:
  path: /api/login
  controller: App\Controller\FrontController::loginPlayer
  methods: PATCH

api_update_player:
  path: /api/player_settings
  controller: App\Controller\FrontController::updatePlayer
  methods: PATCH

api_delete_player_account:
  path: /api/delete_account
  controller: App\Controller\FrontController::deletePlayerAccount
  methods: DELETE

#GAMES

api_create_game:
  path: /api/create_game
  controller: App\Controller\FrontPlayerGameController::createGame
  methods: POST

api_login_game:
  path: /api/join_game
  controller: App\Controller\FrontPlayerGameController::joinGame
  methods: PATCH