controllers:
  resource: ../src/Controller/
  type: annotation

kernel:
  resource: ../src/Kernel.php
  type: annotation

api_index:
  path: /api
  controller: App\Controller\ApiController::index
  methods: GET

# PLAYERS

api_get_players:
  path: /api/players
  controller: App\Controller\PlayerController::getAllPlayers
  methods: GET

api_get_player:
  path: /api/players/{id}
  controller: App\Controller\PlayerController::getPlayer
  methods: GET

api_post_player:
  path: /api/players
  controller: App\Controller\PlayerController::postPlayer
  methods: POST

api_put_player:
  path: /api/players/{id}
  controller: App\Controller\PlayerController::putPlayer
  methods: PUT

api_delete_player:
  path: /api/players/{id}
  controller: App\Controller\PlayerController::deletePlayer
  methods: DELETE

# GAMES

api_get_games:
  path: /api/games
  controller: App\Controller\GameController::getAllGames
  methods: GET

api_post_game:
  path: /api/games
  controller: App\Controller\GameController::postGame
  methods: POST
